export { plugin as ApiDocs } from "@backstage/plugin-api-docs"
export { catalogPlugin as CatalogPlugin } from "@backstage/plugin-catalog"
export { plugin as TechRadar } from "@backstage/plugin-tech-radar"
export { plugin as GraphiQL } from "@backstage/plugin-graphiql"
export { todoPlugin } from "@backstage/plugin-todo"
